package hello;
// Generated Oct 19, 2006 3:36:08 PM by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="MESSAGES"
    ,schema="PUBLIC"
    , uniqueConstraints = {  }
)
public class Message  implements java.io.Serializable {

    // Fields    

     private long id;
     private Message messages;
     private String text;
     private Set<Message> messageses = new HashSet<Message>(0);

     // Constructors

    /** default constructor */
    public Message() {
    }

    /** full constructor */
    public Message(Message messages, String text, Set<Message> messageses) {
       this.messages = messages;
       this.text = text;
       this.messageses = messageses;
    }
   
    // Property accessors
     @GenericGenerator(name="generator", strategy="increment", parameters = { } )
@Id @GeneratedValue(generator="generator")
    
    @Column(name="MESSAGE_ID", unique=true, nullable=false, insertable=true, updatable=true)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="NEXT_MESSAGE_ID", unique=false, nullable=true, insertable=true, updatable=true)
    public Message getMessages() {
        return this.messages;
    }
    
    public void setMessages(Message messages) {
        this.messages = messages;
    }
    
    @Column(name="MESSAGE_TEXT", unique=false, nullable=true, insertable=true, updatable=true)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="messages")
    public Set<Message> getMessageses() {
        return this.messageses;
    }
    
    public void setMessageses(Set<Message> messageses) {
        this.messageses = messageses;
    }




}


